language: java
#sudo: required only required when using docker or when you are using sudo commands
sudo: false

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8

services:
  - docker

notifications:
  email: false

# Set up notification options
#notifications:
#  email:
#    recipients:
#      - one@example.com
#      - other@example.com
#
    # change is when the repo status goes from pass to fail or vice versa
#    on_success: change
#    on_failure: always

install: #forcing a maven install instead of the default maven wrapper install
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

#any console commands can be executed here
script:
  - echo this is an example
  - ls
  - ls target
  - mvn -Dtest=* test
  - echo $TRAVIS_JDK_VERSION

  # Go to docker directory for the dockerfile
  - cd /home/travis/build/xebia-research/headerbuddy/target/docker

  # Creating image from dockerfile
  - docker build -t xebia/headerbuddy .

  # Create the container
  - docker run -it -d --name headerbuddy-container -p 8080:8080 xebia/headerbuddy

  # List all docker containers
  - docker ps

  # Run integration tests
  - cd /home/travis/build/xebia-research/headerbuddy/

  # curl to check if dockerized API is running
  - curl -v http://localhost:8080/helloworld