language: java
#sudo: required only required when using docker or when you are using sudo commands
sudo: false

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8

services:
  - docker

notifications:
  email: false

# Set up notification options
#notifications:
#  email:
#    recipients:
#      - one@example.com
#      - other@example.com
#
    # change is when the repo status goes from pass to fail or vice versa
#    on_success: change
#    on_failure: always

install: #forcing a maven install instead of the default maven wrapper install

  - mvn install -Dmaven.javadoc.skip=true -B -V

#any console commands can be executed here
script:

  # Go to docker directory for the dockerfile
  - cd target/docker

  # Creating image from dockerfile
  - docker build -t xebia/headerbuddy .

  # Pull database image
  - docker pull mysql

  # Create database container
  - docker run --detach --name=mysql-headerbuddy --env="MYSQL_ROOT_PASSWORD=usbw" --env="MYSQL_DATABASE=headerbuddy" --publish 6603:3306 mysql

  # Create the application container
  - docker run -it -d --name headerbuddy-container -p 8080:8080 xebia/headerbuddy

  # Return to root map
  - cd ..
  - cd ..

  #pull the owasp zap container
  - docker pull owasp/zap2docker-stable

  #run the container and test the app
  - docker run -t owasp/zap2docker-stable zap-baseline.py -t http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):8080

  - docker ps

  # curl to check if dockerized API is running
  - curl -v http://localhost:8080/headerbuddy/api?url=https://www.google.com


