language: java
#sudo: required only required when using docker or when you are using sudo commands
sudo: false

before_script:
  - sudo /etc/init.d/mysql stop

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8

services:
  - docker

notifications:
  email: false

# Set up notification options
#notifications:
#  email:
#    recipients:
#      - one@example.com
#      - other@example.com
#
    # change is when the repo status goes from pass to fail or vice versa
#    on_success: change
#    on_failure: always

install: #forcing a maven install instead of the default maven wrapper install

  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

#any console commands can be executed here
script:

  - mvn clear package -DskipTests=true
  
  # Create docker database container
  - docker-compose up -d db

  # Give the mySQL database time to totally finish starting up
  - sleep 15

  # Create the application container
  - docker-compose up -d headerbuddy

  - docker logs headerbuddy_headerbuddy_1

  - docker ps

  # Give the application time to finish starting up
  - sleep 15

  - docker ps

  # Run all tests
  - mvn -Dspring.datasource.url=jdbc:mysql://localhost:3306/headerbuddy verify

  - docker ps

  #pull the owasp zap container
  - docker pull owasp/zap2docker-stable

  - docker ps

  #run the container and test the app
  - docker run -t owasp/zap2docker-stable zap-baseline.py -t http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):8080

  - docker ps

